sudo: false
language: python
python:
  - "2.6"
  - "2.7"
cache:
  directories:
    - $HOME/.local/share/pystanforddeps
install: pip install --user jpype1
script:
  - pip install --user .
  - nosetests
